-- OCP Staff Selection / Employee Database Monitoring
-- Run this once in Supabase SQL Editor.

create table if not exists public.staff_records (
    id bigint generated by default as identity primary key,
    name text not null default '',
    position text not null default '',
    type_of_engagement text not null default '',
    evaluation text not null default '',
    status text not null default '',
    project text not null default '',
    source_file text not null default '',
    source_path text not null default '',
    uploaded_at timestamptz not null default now()
);

create index if not exists staff_records_source_file_idx on public.staff_records(source_file);
create index if not exists staff_records_project_idx on public.staff_records(project);
create index if not exists staff_records_status_idx on public.staff_records(status);

-- Storage bucket for the original Excel/CSV files.
insert into storage.buckets (id, name, public)
values ('ocp-staff-files', 'ocp-staff-files', false)
on conflict (id) do nothing;

-- The Streamlit app should use the Supabase service-role key in Streamlit Secrets.
-- Therefore, RLS does not need public policies for this server-side app.
-- Do not expose the service-role key in source code or GitHub.
